### ISSUE TITLE
Error with PIL

### ISSUE THREAD

**Issue by MeekOnGithub** [krishsharma0413/DiscordLevelingCard#3]
Hey, there is an error with your module using PIL

```
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x0000025B06394190>:
Traceback (most recent call last):
  File "C:\Users\Zaidorox\AppData\Local\Programs\Python\Python310\lib\site-packages\nextcord\application_command.py", line 824, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "C:\Users\Zaidorox\Desktop\Evolium bot\Evolium.py", line 545, in user_rank_card
    image = await a.card1()
  File "C:\Users\Zaidorox\AppData\Local\Programs\Python\Python310\lib\site-packages\DiscordLevelingCard\discord_card.py", line 142, in card1
    draw.text((205,(327/2)+20), self.username,font=myFont, fill=self.text_color,stroke_width=1,stroke_fill=(0, 0, 0))
  File "C:\Users\Zaidorox\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageDraw.py", line 408, in text    if self._multiline_check(text):
  File "C:\Users\Zaidorox\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageDraw.py", line 370, in _multiline_check
    return split_character in text
TypeError: argument of type 'Member' is not iterable

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: TypeError: argument of type 'Member' is not iterable

**Comment by ResetXD** [comment]
Can you show me the code?
